import type { Metadata } from "next";
import { Inter,Dancing_Script } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Navigation/Nav";
import Head from "next/head";
const inter = Inter({ subsets: ["latin"] });
const dancingScript = Dancing_Script({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={inter.className} >
        <Nav dancingScriptClass={dancingScript.className}/>
        {children}</body>
    </html>
  );
}
